AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Documentation:
  Enabled: false
